# Generated by Django 4.0.4 on 2022-05-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
